feat: Metadata storage class w/ RocksDB

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -37,9 +37,13 @@ fi
 # Change into the build directory.
 cd "${BUILD_DIR}" || exit 127
 
+# Define the vcpkg toolchain file path.
+VCPKG_TOOLCHAIN_FILE="/home/vagrant/vcpkg/scripts/buildsystems/vcpkg.cmake"
+
 # Run CMake to configure the project.
-echo "Running cmake .."
-cmake .. || { echo "cmake configuration failed"; exit 1; }
+echo "Running cmake with vcpkg: cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_TOOLCHAIN_FILE} .."
+cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_TOOLCHAIN_FILE} .. || { echo "cmake configuration failed"; exit 1; }
+
 
 # Build the project using make with all available cores.
 echo "Running make -j"
